import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'category',
      label: 'Useful Resources',
      className: 'label-gluex-powerful',
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'Discord Support',
          href: 'https://discord.gg/8W82hJwWbW',
          className: 'sidebar-external-link',
        },
        {
          type: 'link',
          label: 'Telegram Community',
          href: 'https://t.me/+yf_US2ACNrgyNzY0',
          className: 'sidebar-external-link',
        },
        {
          type: 'link',
          label: 'X',
          href: 'https://x.com/GluexProtocol',
          className: 'sidebar-external-link',
        },
        {
          type: 'link',
          label: 'Github',
          href: 'http://github.com/gluexprotocol',
          className: 'sidebar-external-link',
        },
      ],
    },
  ],
};

export default sidebars;
